apiVersion: v1
kind: Secret
metadata:
  name: codeflix-auth-secret
type: Opaque
data:
  KEYCLOAK_ADMIN: "ZXBzY2F2YWxjYW50ZQ=="
  KEYCLOAK_ADMIN_PASSWORD: "SEBzaEBzaDFu"
  KC_DB_URL: "amRiYzpteXNxbDovLzM0LjQyLjI2LjE4OTozMzA2L2NvZGVmbGl4LWtleWNsb2Fr"
  KC_DB_USERNAME: "Y29kZWZsaXgtYXV0aA=="
  KC_DB_PASSWORD: "Q29kZWZsaXhAQXV0aA=="